version: '3.8'

services:
  frontend:
    build:
      context: ./NEW_FRON/seguridadNacional
      dockerfile: Dockerfile
    container_name: seguridad_frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "5173:5173"
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge